# Generic dataset-preparation settings for this source dataset.
# Paths are relative to this config file. This config assumes source labels are YOLO detection txt files.
dataset_name: MBDD2025
source_images: ../datasets/MBDD2025/JPEGImages
source_labels: ../datasets/MBDD2025/Labels
output: ../datasets/mbdd2025
classes:
  - crack
  - leakage
  - abscission
  - corrosion
  - bulge
validation_fraction: 0.2
seed: 17
link_files: true
